grammars/coffeescript (literate).cson
grammars/coffeescript.cson
spec/coffee-script-spec.coffee

The construction `{,2}` in regular expressions is only supported by Oniguruma (which is used by Atom). This Atom bundle is used to highlight CoffeeScript code on GitHub. However, GitHub is using a [PCRE-based engine](https://github.com/vmg/pcre) for regexes.
This pull request fixes that by using an explicit count modifier in the regex.

Explicit test modifiers

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

I figured an issue when using to insert Javascript inside my CoffeeScript file.
In order to fix it, I searched for the similar plugin used by Sublime text.
You can find the reference here : 
https://github.com/aponxi/sublime-better-coffeescript/blob/master/CoffeeScript_Literate.tmLanguage#L668
To help you visualize the problem, here is a before/after capture : 
Before this fix :
After this fix :
I'm here to help if you have more questions :) Thanks

Fix regexp to detect backticks

---

grammars/coffeescript.cson

All the spacings, newlines and tabs (e.g. \n\t\t\t) should not be in the grammar. It seems like these spacings were carried over from the tmbundle during conversion.
The same applies to literate coffeescript. I haven't had the time to clean it up in this PR.

Fix extra spacings due to conversion from tmbundle

---

grammars/coffeescript (literate).cson

Instead of removing `\n` and `\t`, I have replaced them with new lines and 2 spaces. This makes it easier to read and matches the original tmbundle format.

Update coffeescript literate spaces

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

This PR does two things:
1. Remove duplicate tokens.  The `variable.assignment` tokens were being duplicated, so I fixed that.
2. Fix token boundaries.  Some whitespace was being tokenized inadvertently (eg `a ` being tokenized as `entity.name.function`, which isn't right.

Fix duplicate tokens and token boundaries

---

grammars/coffeescript (literate).cson
spec/coffee-script-literate-spec.coffee

Fixes #71
Also took the liberty of reformatting some of them and removing the useless folding markers.
A skeleton `coffee-script-literate-spec.coffee` has been added to prevent this from happening in the future.
/cc @adrianlee44 
@davibe, @B34rPG: if you two could clone this branch and then `apm link` it to see if it fixes your issue, that would be fantastic.

Encase extended regexes in triple quotes

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

An attempt at fixing #75
New specs pass and no known regressions, but could use review, since I’m not familiar with these grammar files. 
Thanks for the pointer on running the specs. Is there a way I can symlink my copy of the library with Atom just to see the syntax highlighting in action?

Fix for Issue #75

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

This is basically the same as #65, except I've fixed a very large mistake that the specs weren't catching.  I was accidentally only matching the first letter of a variable instead of the whole thing, which the specs didn't catch because they only tested one-character-long variables :/.
/cc @kevinsawicki

Correct some incorrect scopes

---

settings/language-coffee-script.cson

I brewed a [small Chai plugin](https://github.com/DanBrooker/file-icons/blob/3109ce811728070e9d0077b4eb45936ef878df4a/lib/bin/run-tests#L13-L29) to check an HTML element's `classList` for one or more classes:
To say it in spec-ese, `it "should not have done that", ->`.

Prevent ".class" from triggering an auto-indent

---

grammars/coffeescript (literate).cson
grammars/coffeescript.cson
spec/coffee-script-literate-spec.coffee
spec/coffee-script-spec.coffee

Copy+pasta from 5846f59:
* **Added:** Hashbang recognition for Literate CoffeeScript
* **Fixed:** Incorrect boundary matching of existing hashbang; previously, a line like `#!/projects/coffeelabs/run` would've triggered the grammar.
* **Added:** Modeline support for Emacs and Vim. Neither editor supports the language out-of-the-box, but community-authored modes exist, both with the typical mode-name choices of `coffee` and `litcoffee`.
**See:**
- https://github.com/kchmck/vim-coffee-script
- https://github.com/defunkt/coffee-mode
- https://github.com/jashkenas/coffeescript/wiki/Text-editor-plugins

Extend firstLineMatch support to include modelines

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Fixes #57
I also took the liberty of rescoping some things (for example, `{` is *clearly* not a `keyword.operator`).
This regex might be able to be cleaned up a bit more...I would do the following, but I'm not sure if everything that would match is valid:
```coffee
'begin': '(?<=\\s|^)({)(?=(.+?)}\\s+=)'
'beginCaptures':
'1':
'name': 'punctuation.definition.destructuring.begin.bracket.curly.coffee'
'2':
'patterns': [
{
}
]
```
Some advice from someone who's more seasoned with Coffeescript would be nice.

Don't blindly eat tokens when trying to match destructuring assignments

---

settings/language-coffee-script.cson

Simple change: if the last character on a line is a colon, increase the next line's indentation level.
None.
Much less tabbing when writing CSON.  Now only shift-tabbing!... :(
I went through a quick mental checklist and couldn't think of any scenario where you wouldn't want the next line to be indented, but I could be wrong.
None.

Auto-indent colons

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

We now use a `match` instead of a begin/end because regexes can only be on a single line.  In addition, we now check to make sure that there is no word following the end of a potential regex expression, as that would be invalid.
None.
Potentially more accurate regex detection and differentiation between division.
Regex detection is ripe for regressions, as can be seen by #112.  Combined with the lack of specs...
Fixes #112
@GarmOfGnipahellir, @julians, @ezekg, @1j01 if one of you could please test this out and let me know the results, that would be …

Provide more accurate regex detection

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Decided to do this before the JSDoc grammar starts getting hairy. It enables a user to style the first backslash of a double-escape with their stylesheet:
~~~less
.@{_}coffee{
&.@{_}string{
.@{_}punctuation.@{_}definition.@{_}escape.@{_}backslash{
opacity: .2;
}
}
}
~~~
Which yields noticeable improvement to readability when you're working with CSON grammars:
~~I haven't added specs because I want to focus on atom/language-javascript#495. I figured if I was going through the trouble of forking and dev-linking another package to make another job easier, I may as well share it.~~
~~Let me know if you still want me to add specs; but I won't get to it instantly.~~
**EDIT:** Belay that, specs added.
FTR, it actually *is* possible to target the first character using the `::first-letter` …

Tokenise backslash in escape sequences

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Stop matching regex at the first non-escaped forwards slash.
None.
Prevents highlighting errors when other forward slashes are further down the line
None.
Fixes #118
/cc @as-cii

Stop regex at the first non-escaped forwards slash

---

grammars/coffeescript.cson

Added the following keywords for [es2015 module syntax support](http://coffeescript.org/#modules):
- import
- export
- default
- as
- from
For [async/await and generators](http://coffeescript.org/v2/#fat-arrow):
- async
- await
- yield
None.
Code using the new features will be more readable.
Functions with the same name as the new keywords _might_ look a little awkward.
None.

Added new keywords to bring package up to date with CoffeeScript 1.12 and 2.0

---

grammars/coffeescript.cson

Depending on the regular expression engine used, \h does not always
mean the same. With a PCRE engine, it matches white spaces, whereas,
with a Oniguruma engine, it matches hexademical digit characters.
Atom uses an Oniguruma engine, but github.com relies on a PCRE
engine.
None were considered.
Makes the grammar PCRE-compatible, so that it can be used on github.com.
I don't have any way to check these PCRE vs. Oniguruma discrepancies at the moment. I'm working on a new test at the Linguist-level to check for all known discrepancies.

Avoid using the ambiguous \h shorthand character

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

The regex regex just keeps getting regexier.  Who doesn't like a negative lookahead in a lookahead? 
Now a begin/end match in an attempt to avoid some _very ugly_ lookbehinds that may not even be possible.
Attempt to use lookbehinds.
Maybe this will be the last regex fix.
Maybe this won't be the last regex fix.
Fixes #127
/cc @Alhadis

Match regexes containing multiple escaped forward slashes

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Clamps embedded JS patterns to always end at <code>`</code>.
A multiline pattern could be kept but with an additional subpattern specifically targeting JS comments, as is done in HTML.
No runaway JS code.
Multiline embedded JS is no longer possible.
Fixes #146

Clamp embedded JS patterns

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

This removes the pattern that was forcing block comments to always be multiline.  However, doing so has exposed more bugs with function tokenization breaking on comments.  I'll see if it can be fixed in this PR.
N/A
Single-line block comments will be tokenized correctly.
There are no drawbacks, per say, but as mentioned above this change does reveal some more underlying bugs.
Fixes #149

Block comments are not necessarily multiline

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Adds support for `..` and `...` in arrays.  Leftover from #103.
None.
No weird period highlighting in arrays.
This should work smoothly as `[` and `]` are always used to denote arrays.
Fixes #144

Tokenize slices

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

`and=` and `or=` were being lumped with the other compound assignment operators, which since they're symbols do not require any whitespace around the operator.  `and=` and `or=` however do require whitespace since they're English.  Therefore, extract those two into their own pattern with proper boundary checking (identifier + spaces, or no identifier before the operator).
None.
`operand=`, `editor=` will be tokenized correctly.
None.
Fixes #152

Add proper boundary-checking for and=, or=

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Separate function/method call matching into two categories: calls with parentheses and calls without.  This prevents the grammar from starting an argument list without parentheses but then ending it _with_ a parenthesis.  This can happen, for example, when the function call is wrapped in parentheses like so: `(eat food)`.
None.
Argument list tokenization is now consistent: no more potential for mixed parentheses matching.
None.
Fixes #153
Fixes #154
Fixes #155
/cc @nathancarter: Thanks so much for the detailed issues that you created.  They really helped …

Differentiate between function/method calls with and without parentheses

---

.coffeelintignore
grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Just a simple, tiny fix: double-quoted heredocs are scoped with `string.quoted.double.heredoc`, but there's nothing to identify heredocs which are delimited by three apostrophes:
~~~cson
string: '''
Heredoc
'''
~~~
**UPDATE:**  
I've added a scope to identify multiline regular expressions, too:
~~~cson
regexp: ///
(Stuff | etc)
///
~~~
Easier targeting with stylesheets. If a user wishes to style only single-quoted heredocs, they need to resort to duplicated rulesets, or sticking `:not(.double)` in the selector.

Add scope to identify single-quoted heredocs

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

The parentheses location was wrong causing `classTest` to match.
Fixes #161

Adjust word boundary matches when matching a class constructor

---

grammars/coffeescript.cson
spec/coffee-script-spec.coffee

Continuation of #156 and 43d6b9deb7294b9e7c03c6d39028ffb643ad0df7, this time for square brackets.
None.
Correct termination of arguments when function/method calls are in an array.
None.
Fixes #163

Stop arguments on all three brackets
